server:
  port: 8080
  ssl:
    key-store: classpath:maoyou.site.jks
    key-store-password: xx10daor0vb
    key-store-type: JKS
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wallpaper
    username: hong
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${wallpaper.imagesPath}
wallpaper:
  imagesPath: /home/ubuntu/hong/wallpaper/



